### ISSUE TITLE
Creates an Util Class

### ISSUE THREAD

**Issue by ffarzat** [ffarzat/JavaScriptHeuristicOptmizer#61]
- [ ] NPM install
- [ ] NPM Test
- [ ] Copy full directory for tests

**Comment by andrefarzat** [comment]
an `Util` class? Like a static class with utils methods?

**Comment by ffarzat** [comment]
Exatly. The real name maybe NPMHelper or something like that. It will be usefull for npm commands and workarrounds for it (npm).
